[ids]
*

[main]
capslock = overload(control, esc)
tab = overload(tabnav, tab)

[control]
tab = C-tab

[alt]
tab = A-tab

[tabnav]
1 = f1
2 = f2
3 = f3
4 = f4
5 = f5
6 = f6
7 = f7
8 = f8
9 = f9
0 = f10
- = f11
= = f12
w = (
e = )
s = {
d = }
x = [
c = ]
r =
f = >
g = ;
v = =
h = left
j = down
k = up
l = right
y = home
o = end
u = pageup
m = pagedown
